### PR TITLE
ilrepack.sh is failing - it deosn't find Lucene.Net.

### PR DESCRIPTION
**Pull request by gkarabin**
Without this change I get a broken assembly reference when
building the solution.

### CODE REVIEW

**Comment by mrward** [comment]
Mmm, I have not needed to do this in the past. Lucene.Net is distributed with the addin separately.

**Comment by gkarabin** [comment]
I guess I misinterpreted the resolution. 

The more interesting part is that when I built the solution (after running ilrepack.sh) there was a missing reference to the Nuget assembly in the references list , and a compile-time error with a missing reference to Lucene.Net.

This approach got me a build that worked locally.  I wonder if there’s a difference between my otherwise-not-developing-for-monodevelop machine and yours that supplies Lucene.Net for you and not for me.

**Comment by mrward** [comment]
Yeah I do not have a problem with ILMerging Lucene.Net - not sure why I did not include it. Seems like a reasonable thing to do to avoid conflicts with a possible different version in VS Mac. So I will take a look at including your fix.

Originally the addin was including NuGet.exe with Lucene.NET but in more recent NuGet versions they made a lot of types private in NuGet.exe but not in the separate assemblies so I had to switch over to using the separate assemblies. Since these same assemblies ship with VS Mac things break when those are updated in the main IDE, which is the reason for the merging.

I will most likely need to publish new versions of this and other addins anyway unless I can get the addin server maintainer to fix it on that side. Some addins seem to be OK but some are pointing to the old VS Mac 7.0 versions even though a different version was uploaded for 8.0. I thought I had made a mistake but the uploaded .mpack files look OK.

**Comment by mrward** [comment]
I rebased and included into the master branch. Thanks.

**Pull request closed without merging**
